### ISSUE TITLE
$JOB:DELETE

### ISSUE THREAD

**Issue by Gj-Altie** [SMATechnologies/opcon-cli-java#10]
Hi,

I have two quesions:

Would it be possible to add the schedule date to the output of the GetEstimatedStartTime Function?

Example of old utility:	Estimated Start time for Job EindeTestBatch of Schedule C-ASSIST-TEST-Selfservice **on Schedule Date 04/06/2020** is : 04/06/2020 : 22:55
Example of new utility:	Estimated Start time for Job EindeTestBatch of Schedule C-ASSIST-TEST-Selfservice is 04/06/2020 : 20:43

We could use the current date but this makes the calculation a bit more reliable.

Would it also be possible to add a $JOB:DELETE property?
When the end time of the schedule is exceeded, we want to remove the adhoc job which is responsible for the late end time.   

Thanks in advance

Best regards,

Gertjan Altenburg

**Comment by Bertievh** [comment]
Message changed to include Schedule Date as requested.
Unfortunately, there is no DELETE functionality for jobs in the Daily yet.
Possibly you can use a Cancel or Skip job status change.

**Comment by Bertievh** [comment]
Hi Gertjan,

I have created v 1.1.2 which updates the message to include the Schedule Date.
Unfortunately, there is no DELETE function for a job in the Daily yet.
Would a job action change to cancel or skip work?

Regards
Bertie



Bertie Vanhinsbergen
Principal Automation Consultant
Ziegelbrückstrasse 82 | 8866 Ziegelbrücke
Office: +41 556173643 | Direct: 
www.SMAtechnologies.com
| bvanhinsbergen@smatechnologies.com
The information contained in this e-mail and any accompanying documents may contain information that is confidential or otherwise protected from disclosure. If you are not the intended recipient of this message, or if this message has been addressed to you in error, please immediately alert the sender by reply e-mail and then delete this message, including any attachments. Any dissemination, distribution or other use of the contents of this message by anyone other than the intended recipient is strictly prohibited.​
​
​
