### ISSUE TITLE
Linux -  Could not find or load main class

### ISSUE THREAD

**Issue by andymalo43** [SMATechnologies/opcon-cli-java#16]
Hi, 
I just installed opcon-cli on linux and it doesn't work. I followed every instructions and already have runned it successfully on the windows version.
Here is my error : 
![image](https://user-images.githubusercontent.com/87163807/154911005-6dbd49ed-0202-4c36-a00d-1afb442f104e.png)

Is it possible that it doesn't work because of the authorizations on folders ? Thank you for your help
![image](https://user-images.githubusercontent.com/87163807/154910942-21a3ada9-ef1f-4300-9715-8239477a6536.png)

**Comment by andymalo43** [comment]
Theses firts screens are on  Ubuntu 20.04 installed on WSL1 on my windows computer

Here i'm on a Cento 8 VM where authorizations are set within the .tar.gz file
![image](https://user-images.githubusercontent.com/87163807/154906992-85eb7435-bd50-439d-90cb-e816679b6cf0.png)

I have the same comportement with EncryptValue :(
![image](https://user-images.githubusercontent.com/87163807/154907196-500ff183-e956-4983-9ed6-508e11b3e5d4.png)

**Comment by Bertievh** [comment]
I am sorry, but I do not understand what you are saying.
Please contact a French consultant to help you as unfortunately I do not have time at the moment.

Bertie


Bertie Vanhinsbergen
Senior Developer
Ziegelbrückstrasse 82 | 8866 Ziegelbrücke
Office: +41 5 56 17 36 45 | Direct:
www.SMAtechnologies.com
| ***@***.***
The information contained in this e-mail and any accompanying documents may contain information that is confidential or otherwise protected from disclosure. If you are not the intended recipient of this message, or if this message has been addressed to you in error, please immediately alert the sender by reply e-mail and then delete this message, including any attachments. Any dissemination, distribution or other use of the contents of this message by anyone other than the intended recipient is strictly prohibited.​
​
​
Signature For Bertie Vanhinsbergen

**Comment by Bertievh** [comment]
For some reason the .jar file was missing from the release zip file.
download v1.5

**Comment by andymalo43** [comment]
Hello,

Thank you a lot, it works fine now :)


Le 21/02/2022 à 22:13, Bertievh a écrit :
