### ISSUE TITLE
GetEstimatedStartTime

### ISSUE THREAD

**Issue by Gj-Altie** [SMATechnologies/opcon-cli-java#9]
Would it be possible to add the GetEstimatedStartTime Function?

Thanks in advance ..

**Comment by oeil** [comment]
Hi @Gj-Altie - can you give us a bit more information about what you'd like to accomplish with this function?

Thanks

**Comment by Bertievh** [comment]
Francois,

This was an existing function that I created for Vivat in the Utilities.
Essentially it returns the estimated start time of a specific job in the daily schedule.

During the day on a specific schedule, jobs are added to the schedule as required.
The specific job is the last job in the schedule and provides the estimated start time
of the job which is recalculated every time another job is added to the schedule.

They use this to provide the overnight monitoring organization an estimated completion
time so they can call out people if the processing is not completed by this time. It was
one of the utilities developed a long time ago so they could move there production
controllers to a single shift.

GetEstimatedStartTime
The GetEstimatedStartTime program extracts the estimated start time for a job from the Daily tables. It should be noted that a valid value will only be returned once the StartTimeCalculator has performed the calculations for the job.
GetEstimatedStartTime arguments

GetEstimatedStartTime supports the following arguments (please note all arguments are case sensitive).



Argument

Value

-date
(optional) the date to check (format DD/MM/YYYY). If omitted, defaults to current date.

-job
The name of the job to get the estimated start time for

NOTE :
Both schedule and job must exist in the daily tables for the selected date.
If the job name contains spaces the value should be enclosed within quotes (i.e. "job name").

-schedule
The name of the schedule that contains the job to be get the estimated start time for.

NOTE :
Both schedule and job must exist in the daily tables for the selected date.
If the schedule name contains spaces the value should be enclosed within quotes (i.e. "schedule name").

Table 20 : GetEstimatedStartTime arguments
Examples

[[UTILDIR]]\GetEstimatedStartTime -schedule SCHED001 -job JOB015 -date 17/07/2012

[[UTILDIR]]\GetEstimatedStartTime -schedule "TEST BATCH" -job "TEST JOB" -date 17/07/2012

Francois, when you have completed the refactoring, I will add this function.

Regards
Bertie


Bertie Vanhinsbergen
Principal Automation Consultant
Ziegelbrückstrasse 82 | 8866 Ziegelbrücke
Office: +41 556173643 | Direct: 
www.SMAtechnologies.com
| bvanhinsbergen@smatechnologies.com
The information contained in this e-mail and any accompanying documents may contain information that is confidential or otherwise protected from disclosure. If you are not the intended recipient of this message, or if this message has been addressed to you in error, please immediately alert the sender by reply e-mail and then delete this message, including any attachments. Any dissemination, distribution or other use of the contents of this message by anyone other than the intended recipient is strictly prohibited.​
​
​

**Comment by Gj-Altie** [comment]
I couldn't have explained that better :-)

If more info is needed please let us know

Greetings,

Gj.

**Comment by Bertievh** [comment]
Gertjan,
request implemented.
This has been implemented as a JobAction, see documentation
